In [ ]:
import pandas as pd
import glob
import os

In [ ]:
csv_files = ['wholesale_price.csv','oil_price.csv','inr_usd.csv','iip_index.csv','cpi_index.csv']

In [ ]:
df_list=[]
for file in csv_files:
  df_list.append(pd.read_csv(file))

In [ ]:
combined_df = pd.concat(df_list, axis=1)
print("Combined data shape:",combined_df.shape)

Combined data shape: (156, 6)

In [ ]:
with pd.option_context('display.max_rows', None, 'display.max_columns', None):
    display(combined_df)

       WPI  Price_USD  USD_INR  IIP_Index     Date  YoY_Inflation_Rate
0    113.6      108.0    62.18      114.7  2014-01                8.91
1    113.6      109.0    62.20      111.4  2014-02                8.03
2    114.3      107.0    61.10      125.7  2014-03                8.31
3    114.1      108.0    60.07      108.6  2014-04                8.59
4    114.8      109.0    59.44      113.5  2014-05                8.28
5    115.2      112.0    59.70      113.5  2014-06                7.46
6    116.7      107.0    59.71      111.8  2014-07                7.96
7    116.6      102.0    60.50      110.1  2014-08                7.03
8    116.4       97.0    60.95      111.9  2014-09                6.46
9    115.9       87.0    61.30      107.0  2014-10                4.62
10   114.1       79.0    61.90      112.5  2014-11                3.27
11   112.1       62.0    62.80      119.5  2014-12                4.28
12   110.8       48.0    62.20      118.8  2015-01                4.38
13   110.6       58.0    62.10      116.5  2015-02                4.92
14   110.0       56.0    62.50      131.2  2015-03                4.90
15   109.1       59.0    62.30      112.1  2015-04                4.60
16   110.4       64.0    63.69      116.2  2015-05                4.64
17   110.8       61.0    63.80      117.8  2015-06                5.13
18   111.1       54.0    63.50      116.5  2015-07                3.88
19   110.4       47.0    64.00      116.3  2015-08                3.66
20   110.3       48.0    65.40      116.2  2015-09                4.47
21   110.1       48.0    65.00      120.3  2015-10                4.42
22   109.9       44.0    66.10      108.0  2015-11                5.90
23   109.4       38.0    66.30      119.4  2015-12                5.67
24   108.0       31.0    67.30      117.2  2016-01                5.03
25   107.1       32.0    68.20      116.9  2016-02                4.60
26   107.7       38.0    67.10      130.6  2016-03                4.50
27   109.0       42.0    66.54      113.8  2016-04                5.40
28   110.4       47.0    67.20      118.9  2016-05                5.70
29   111.7       48.0    67.87      119.5  2016-06                5.77
30   111.8       45.0    67.13      115.1  2016-07                6.07
31   111.4       46.0    66.90      114.8  2016-08                5.05
32   111.4       47.0    66.70      117.1  2016-09                4.39
33   111.5       50.0    66.70      125.4  2016-10                4.20
34   111.9       45.0    68.10      115.2  2016-11                3.63
35   111.7       53.0    67.90      122.3  2016-12                3.41
36   112.6       55.0    68.15      121.3  2017-01                3.17
37   113.1       55.0    66.90      118.4  2017-02                3.65
38   113.2       52.0    65.80      133.5  2017-03                3.89
39   113.2       53.0    64.45      117.3  2017-04                2.99
40   112.9       50.0    64.55      123.0  2017-05                2.18
41   112.7       46.0    64.40      120.1  2017-06                1.46
42   113.9       48.0    64.27      118.3  2017-07                2.36
43   114.8       51.0    63.74      122.3  2017-08                3.28
44   114.9       55.0    64.30      123.6  2017-09                3.28
45   115.6       57.0    64.67      122.5  2017-10                3.58
46   116.4       62.0    64.80      126.2  2017-11                4.88
47   115.7       64.0    64.20      131.5  2017-12                5.21
48   116.0       69.0    63.60      130.5  2018-01                5.07
49   116.1       65.0    64.30      127.3  2018-02                4.44
50   116.2       66.0    64.90      141.0  2018-03                4.28
51   117.3       71.0    66.20      123.1  2018-04                4.58
52   118.3       77.0    67.50      130.0  2018-05                4.87
53   119.1       74.0    68.43      128.4  2018-06                4.92
54   119.9       74.0    68.73      126.1  2018-07                4.17
55   120.1       73.0    70.10      128.6  2018-08                3.69
56   120.9       79.0    72.23      129.5  2018-09                3.70
57   122.0       81.0    73.44      133.0  2018-10                3.38
58   121.6       65.0    72.50      126.7  2018-11                2.33
59   120.1       56.0    70.70      134.7  2018-12                2.11
60   119.4       59.0    71.24      135.2  2019-01                1.97
61   119.9       64.0    71.10      127.6  2019-02                2.57
62   120.4       66.0    69.50      145.4  2019-03                2.86
63   121.1       71.0    69.35      126.3  2019-04                2.92
64   121.6       70.0    69.70      133.5  2019-05                3.05
65   121.5       63.0    69.40      129.9  2019-06                3.18
66   121.4       64.0    68.82      131.5  2019-07                3.15
67   121.5       59.0    70.99      126.4  2019-08                3.21
68   121.3       62.0    71.30      122.9  2019-09                3.99
69   122.0       59.0    70.83      127.3  2019-10                4.62
70   122.3       63.0    71.50      128.8  2019-11                5.54
71   123.0       66.0    71.10      133.5  2019-12                7.35
72   123.4       64.0    71.32      137.9  2020-01                7.59
73   122.2       55.0    71.50      134.2  2020-02                6.58
74   120.4       32.0    74.20      117.2  2020-03                5.84
75   119.2       18.0    76.30       53.6  2020-04                7.22
76   117.5       32.0    75.60       89.6  2020-05                6.27
77   119.3       40.0    75.80      108.9  2020-06                6.23
78   121.0       43.0    74.80      117.9  2020-07                6.73
79   122.0       45.0    74.90      117.2  2020-08                6.69
80   122.9       41.0    73.69      124.1  2020-09                7.27
81   123.6       40.0    73.40      131.9  2020-10                7.61
82   125.1       43.0    74.10      126.9  2020-11                6.93
83   125.4       50.0    73.60      136.1  2020-12                4.59
84   126.5       55.0    73.10      136.1  2021-01                4.06
85   128.1       61.0    72.80      129.9  2021-02                5.03
86   129.9       65.0    72.70      146.2  2021-03                5.52
87   132.0       65.0    74.10      125.1  2021-04                4.23
88   132.9       68.0    73.20      115.7  2021-05                6.30
89   133.7       73.0    73.14      122.3  2021-06                6.26
90   135.0       74.0    74.50      131.2  2021-07                5.59
91   136.2       70.0    74.34      132.0  2021-08                5.30
92   137.4       74.0    73.60      126.9  2021-09                4.35
93   140.7       83.0    74.92      135.5  2021-10                4.48
94   143.7       81.0    74.34      128.7  2021-11                4.91
95   143.3       74.0    75.40      139.1  2021-12                5.66
96   145.0       86.0    74.50      139.1  2022-01                6.01
97   147.2       94.0    74.64      132.3  2022-02                6.07
98   150.3      115.0    76.20      149.3  2022-03                6.95
99   152.3      104.0    76.49      134.6  2022-04                7.79
100  155.0      111.0    77.50      135.4  2022-05                7.04
101  156.6      117.0    78.10      138.1  2022-06                7.01
102  154.0      105.0    79.60      134.0  2022-07                6.71
103  153.2       98.0    79.35      131.4  2022-08                7.00
104  152.1       90.0    80.20      133.7  2022-09                7.41
105  152.5       93.0    82.30      129.7  2022-10                6.77
106  151.7       91.0    81.97      137.4  2022-11                5.88
107  150.5       81.0    82.74      145.3  2022-12                5.72
108  150.7       82.0    81.90      146.9  2023-01                6.52
109  150.9       82.0    82.22      138.6  2023-02                6.44
110  151.0       78.0    82.53      151.7  2023-03                5.66
111  151.1       83.0    82.02      141.2  2023-04                4.70
112  150.2       75.0    81.72      146.5  2023-05                4.31
113  149.3       75.0    82.43      143.7  2023-06                4.87
114  152.1       80.0    82.15      142.1  2023-07                7.44
115  152.5       85.0    82.68      144.9  2023-08                6.83
116  151.8       93.0    82.72      141.7  2023-09                5.02
117  152.9       89.0    83.25      145.0  2023-10                4.87
118  153.1       82.0    83.15      140.4  2023-11                5.55
119  151.8       77.0    83.30      152.3  2023-12                5.69
120  151.2       79.0    83.11      154.2  2024-01                5.10
121  151.4       82.0    82.97      151.1  2024-02                5.09
122  151.8       85.0    83.03      166.3  2024-03                4.85
123  153.0       89.0    83.40      148.0  2024-04                4.83
124  153.3       82.0    83.35      154.7  2024-05                4.75
125  154.1       83.0    83.48      151.0  2024-06                5.08
126  155.3       85.0    83.59      149.8  2024-07                3.54
127  156.1       81.0    83.88      145.8  2024-08                3.65
128  155.5       74.0    83.80      146.9  2024-09                5.49
129  156.4       75.0    84.02      150.3  2024-10                6.21
130  156.1       72.0    84.38      148.1  2024-11                5.50
131  156.2       73.0    84.97      158.0  2024-12                4.57
132  155.0       78.0    85.76      161.6  2025-01                4.35
133  154.9       85.0    86.55      151.1  2025-02                4.24
134  154.8       80.0    87.10      166.3  2025-03                4.52
135  154.2       72.0    85.85      151.8  2025-04                4.43
136  153.7       68.0    84.51      157.6  2025-05                4.10
137  153.7       71.0    85.77      153.3  2025-06                4.05
138  154.4       76.0    85.23      156.2  2025-07                3.32
139  155.2       82.0    87.11      151.8  2025-08                3.64
140  155.0       75.0    88.17      153.7  2025-09                3.36
141  155.1       73.0    88.72      151.1  2025-10                4.32
142  155.9       71.0    88.68      158.7  2025-11                4.40
143  157.0       68.0    89.89      170.7  2025-12                3.91
144  157.6       75.0    90.73      169.9  2026-01                3.62
145  158.2       88.0    90.76      158.8  2026-02                3.55
146  160.8      103.0    92.89      173.2  2026-03                3.51
147    NaN      115.0    93.39        NaN  2026-04                3.48
148    NaN      111.0    95.31        NaN      NaN                 NaN
149    NaN        NaN    98.27        NaN      NaN                 NaN
150    NaN        NaN    98.79        NaN      NaN                 NaN
151    NaN        NaN    99.51        NaN      NaN                 NaN
152    NaN        NaN   101.69        NaN      NaN                 NaN
153    NaN        NaN   102.27        NaN      NaN                 NaN
154    NaN        NaN   104.19        NaN      NaN                 NaN
155    NaN        NaN   105.50        NaN      NaN                 NaN

In [ ]:
combined_df[['year','month']] = combined_df['Date'].str.split('-', expand=True)
combined_df.head()

,WPI,Price_USD,USD_INR,IIP_Index,Date,YoY_Inflation_Rate,year,month
0,113.6,108.0,62.18,114.7,2014-01,8.91,2014,01
1,113.6,109.0,62.20,111.4,2014-02,8.03,2014,02
2,114.3,107.0,61.10,125.7,2014-03,8.31,2014,03
3,114.1,108.0,60.07,108.6,2014-04,8.59,2014,04
4,114.8,109.0,59.44,113.5,2014-05,8.28,2014,05

In [ ]:
combined_df = combined_df.drop(columns=['Date'])

arrange the columns

In [ ]:
remain_columns = ['year','month','YoY_Inflation_Rate']
other_columns = [col for col in combined_df.columns if col not in remain_columns]
arrange = ['year','month'] + other_columns + ['YoY_Inflation_Rate']
combined_df = combined_df[arrange]

In [ ]:
combined_df.head()

   year month    WPI  Price_USD  USD_INR  IIP_Index  YoY_Inflation_Rate
0  2014    01  113.6      108.0    62.18      114.7                8.91
1  2014    02  113.6      109.0    62.20      111.4                8.03
2  2014    03  114.3      107.0    61.10      125.7                8.31
3  2014    04  114.1      108.0    60.07      108.6                8.59
4  2014    05  114.8      109.0    59.44      113.5                8.28

cleaning the data's

In [ ]:
print(combined_df.dtypes)

year                   object
month                  object
WPI                   float64
Price_USD             float64
USD_INR               float64
IIP_Index             float64
YoY_Inflation_Rate    float64
dtype: object

In [ ]:
print(combined_df.isnull().sum())

year                  8
month                 8
WPI                   9
Price_USD             7
USD_INR               0
IIP_Index             9
YoY_Inflation_Rate    8
dtype: int64

In [ ]:
with pd.option_context('display.max_rows', None, 'display.max_columns', None):
    display(combined_df)

     year month    WPI  Price_USD  USD_INR  IIP_Index  YoY_Inflation_Rate
0    2014    01  113.6      108.0    62.18      114.7                8.91
1    2014    02  113.6      109.0    62.20      111.4                8.03
2    2014    03  114.3      107.0    61.10      125.7                8.31
3    2014    04  114.1      108.0    60.07      108.6                8.59
4    2014    05  114.8      109.0    59.44      113.5                8.28
5    2014    06  115.2      112.0    59.70      113.5                7.46
6    2014    07  116.7      107.0    59.71      111.8                7.96
7    2014    08  116.6      102.0    60.50      110.1                7.03
8    2014    09  116.4       97.0    60.95      111.9                6.46
9    2014    10  115.9       87.0    61.30      107.0                4.62
10   2014    11  114.1       79.0    61.90      112.5                3.27
11   2014    12  112.1       62.0    62.80      119.5                4.28
12   2015    01  110.8       48.0    62.20      118.8                4.38
13   2015    02  110.6       58.0    62.10      116.5                4.92
14   2015    03  110.0       56.0    62.50      131.2                4.90
15   2015    04  109.1       59.0    62.30      112.1                4.60
16   2015    05  110.4       64.0    63.69      116.2                4.64
17   2015    06  110.8       61.0    63.80      117.8                5.13
18   2015    07  111.1       54.0    63.50      116.5                3.88
19   2015    08  110.4       47.0    64.00      116.3                3.66
20   2015    09  110.3       48.0    65.40      116.2                4.47
21   2015    10  110.1       48.0    65.00      120.3                4.42
22   2015    11  109.9       44.0    66.10      108.0                5.90
23   2015    12  109.4       38.0    66.30      119.4                5.67
24   2016    01  108.0       31.0    67.30      117.2                5.03
25   2016    02  107.1       32.0    68.20      116.9                4.60
26   2016    03  107.7       38.0    67.10      130.6                4.50
27   2016    04  109.0       42.0    66.54      113.8                5.40
28   2016    05  110.4       47.0    67.20      118.9                5.70
29   2016    06  111.7       48.0    67.87      119.5                5.77
30   2016    07  111.8       45.0    67.13      115.1                6.07
31   2016    08  111.4       46.0    66.90      114.8                5.05
32   2016    09  111.4       47.0    66.70      117.1                4.39
33   2016    10  111.5       50.0    66.70      125.4                4.20
34   2016    11  111.9       45.0    68.10      115.2                3.63
35   2016    12  111.7       53.0    67.90      122.3                3.41
36   2017    01  112.6       55.0    68.15      121.3                3.17
37   2017    02  113.1       55.0    66.90      118.4                3.65
38   2017    03  113.2       52.0    65.80      133.5                3.89
39   2017    04  113.2       53.0    64.45      117.3                2.99
40   2017    05  112.9       50.0    64.55      123.0                2.18
41   2017    06  112.7       46.0    64.40      120.1                1.46
42   2017    07  113.9       48.0    64.27      118.3                2.36
43   2017    08  114.8       51.0    63.74      122.3                3.28
44   2017    09  114.9       55.0    64.30      123.6                3.28
45   2017    10  115.6       57.0    64.67      122.5                3.58
46   2017    11  116.4       62.0    64.80      126.2                4.88
47   2017    12  115.7       64.0    64.20      131.5                5.21
48   2018    01  116.0       69.0    63.60      130.5                5.07
49   2018    02  116.1       65.0    64.30      127.3                4.44
50   2018    03  116.2       66.0    64.90      141.0                4.28
51   2018    04  117.3       71.0    66.20      123.1                4.58
52   2018    05  118.3       77.0    67.50      130.0                4.87
53   2018    06  119.1       74.0    68.43      128.4                4.92
54   2018    07  119.9       74.0    68.73      126.1                4.17
55   2018    08  120.1       73.0    70.10      128.6                3.69
56   2018    09  120.9       79.0    72.23      129.5                3.70
57   2018    10  122.0       81.0    73.44      133.0                3.38
58   2018    11  121.6       65.0    72.50      126.7                2.33
59   2018    12  120.1       56.0    70.70      134.7                2.11
60   2019    01  119.4       59.0    71.24      135.2                1.97
61   2019    02  119.9       64.0    71.10      127.6                2.57
62   2019    03  120.4       66.0    69.50      145.4                2.86
63   2019    04  121.1       71.0    69.35      126.3                2.92
64   2019    05  121.6       70.0    69.70      133.5                3.05
65   2019    06  121.5       63.0    69.40      129.9                3.18
66   2019    07  121.4       64.0    68.82      131.5                3.15
67   2019    08  121.5       59.0    70.99      126.4                3.21
68   2019    09  121.3       62.0    71.30      122.9                3.99
69   2019    10  122.0       59.0    70.83      127.3                4.62
70   2019    11  122.3       63.0    71.50      128.8                5.54
71   2019    12  123.0       66.0    71.10      133.5                7.35
72   2020    01  123.4       64.0    71.32      137.9                7.59
73   2020    02  122.2       55.0    71.50      134.2                6.58
74   2020    03  120.4       32.0    74.20      117.2                5.84
75   2020    04  119.2       18.0    76.30       53.6                7.22
76   2020    05  117.5       32.0    75.60       89.6                6.27
77   2020    06  119.3       40.0    75.80      108.9                6.23
78   2020    07  121.0       43.0    74.80      117.9                6.73
79   2020    08  122.0       45.0    74.90      117.2                6.69
80   2020    09  122.9       41.0    73.69      124.1                7.27
81   2020    10  123.6       40.0    73.40      131.9                7.61
82   2020    11  125.1       43.0    74.10      126.9                6.93
83   2020    12  125.4       50.0    73.60      136.1                4.59
84   2021    01  126.5       55.0    73.10      136.1                4.06
85   2021    02  128.1       61.0    72.80      129.9                5.03
86   2021    03  129.9       65.0    72.70      146.2                5.52
87   2021    04  132.0       65.0    74.10      125.1                4.23
88   2021    05  132.9       68.0    73.20      115.7                6.30
89   2021    06  133.7       73.0    73.14      122.3                6.26
90   2021    07  135.0       74.0    74.50      131.2                5.59
91   2021    08  136.2       70.0    74.34      132.0                5.30
92   2021    09  137.4       74.0    73.60      126.9                4.35
93   2021    10  140.7       83.0    74.92      135.5                4.48
94   2021    11  143.7       81.0    74.34      128.7                4.91
95   2021    12  143.3       74.0    75.40      139.1                5.66
96   2022    01  145.0       86.0    74.50      139.1                6.01
97   2022    02  147.2       94.0    74.64      132.3                6.07
98   2022    03  150.3      115.0    76.20      149.3                6.95
99   2022    04  152.3      104.0    76.49      134.6                7.79
100  2022    05  155.0      111.0    77.50      135.4                7.04
101  2022    06  156.6      117.0    78.10      138.1                7.01
102  2022    07  154.0      105.0    79.60      134.0                6.71
103  2022    08  153.2       98.0    79.35      131.4                7.00
104  2022    09  152.1       90.0    80.20      133.7                7.41
105  2022    10  152.5       93.0    82.30      129.7                6.77
106  2022    11  151.7       91.0    81.97      137.4                5.88
107  2022    12  150.5       81.0    82.74      145.3                5.72
108  2023    01  150.7       82.0    81.90      146.9                6.52
109  2023    02  150.9       82.0    82.22      138.6                6.44
110  2023    03  151.0       78.0    82.53      151.7                5.66
111  2023    04  151.1       83.0    82.02      141.2                4.70
112  2023    05  150.2       75.0    81.72      146.5                4.31
113  2023    06  149.3       75.0    82.43      143.7                4.87
114  2023    07  152.1       80.0    82.15      142.1                7.44
115  2023    08  152.5       85.0    82.68      144.9                6.83
116  2023    09  151.8       93.0    82.72      141.7                5.02
117  2023    10  152.9       89.0    83.25      145.0                4.87
118  2023    11  153.1       82.0    83.15      140.4                5.55
119  2023    12  151.8       77.0    83.30      152.3                5.69
120  2024    01  151.2       79.0    83.11      154.2                5.10
121  2024    02  151.4       82.0    82.97      151.1                5.09
122  2024    03  151.8       85.0    83.03      166.3                4.85
123  2024    04  153.0       89.0    83.40      148.0                4.83
124  2024    05  153.3       82.0    83.35      154.7                4.75
125  2024    06  154.1       83.0    83.48      151.0                5.08
126  2024    07  155.3       85.0    83.59      149.8                3.54
127  2024    08  156.1       81.0    83.88      145.8                3.65
128  2024    09  155.5       74.0    83.80      146.9                5.49
129  2024    10  156.4       75.0    84.02      150.3                6.21
130  2024    11  156.1       72.0    84.38      148.1                5.50
131  2024    12  156.2       73.0    84.97      158.0                4.57
132  2025    01  155.0       78.0    85.76      161.6                4.35
133  2025    02  154.9       85.0    86.55      151.1                4.24
134  2025    03  154.8       80.0    87.10      166.3                4.52
135  2025    04  154.2       72.0    85.85      151.8                4.43
136  2025    05  153.7       68.0    84.51      157.6                4.10
137  2025    06  153.7       71.0    85.77      153.3                4.05
138  2025    07  154.4       76.0    85.23      156.2                3.32
139  2025    08  155.2       82.0    87.11      151.8                3.64
140  2025    09  155.0       75.0    88.17      153.7                3.36
141  2025    10  155.1       73.0    88.72      151.1                4.32
142  2025    11  155.9       71.0    88.68      158.7                4.40
143  2025    12  157.0       68.0    89.89      170.7                3.91
144  2026    01  157.6       75.0    90.73      169.9                3.62
145  2026    02  158.2       88.0    90.76      158.8                3.55
146  2026    03  160.8      103.0    92.89      173.2                3.51
147  2026    04    NaN      115.0    93.39        NaN                3.48
148   NaN   NaN    NaN      111.0    95.31        NaN                 NaN
149   NaN   NaN    NaN        NaN    98.27        NaN                 NaN
150   NaN   NaN    NaN        NaN    98.79        NaN                 NaN
151   NaN   NaN    NaN        NaN    99.51        NaN                 NaN
152   NaN   NaN    NaN        NaN   101.69        NaN                 NaN
153   NaN   NaN    NaN        NaN   102.27        NaN                 NaN
154   NaN   NaN    NaN        NaN   104.19        NaN                 NaN
155   NaN   NaN    NaN        NaN   105.50        NaN                 NaN

change the data type and remove the nan values

In [ ]:
#droping the nan values
combined_df = combined_df.dropna()

In [ ]:
combined_df['year'] = combined_df['year'].astype(int)
combined_df['month'] = combined_df['month'].astype(int)

/tmp/ipykernel_5588/596266319.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  combined_df['year'] = combined_df['year'].astype(int)
/tmp/ipykernel_5588/596266319.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  combined_df['month'] = combined_df['month'].astype(int)

In [ ]:
print(combined_df.dtypes)

year                    int64
month                   int64
WPI                   float64
Price_USD             float64
USD_INR               float64
IIP_Index             float64
YoY_Inflation_Rate    float64
dtype: object

In [ ]:
print(combined_df.isnull().sum())

year                  0
month                 0
WPI                   0
Price_USD             0
USD_INR               0
IIP_Index             0
YoY_Inflation_Rate    0
dtype: int64

now ill export the proper csv in next colab file for proper feature scalling and train

In [ ]:
# Saving the cleaned DF to a new CSV file
combined_df.to_csv('inflation_detection.csv', index=False)

print("File saved successfully!")

File saved successfully!